Frontend/feature/191 add frontend deploy GitHub actions
bounswe/bounswe2024group1 pull request #192
Opened 2024-05-12 14:56 UTC by boraykasap

2024-05-12 15:06 UTC, mmtftr requested changes

2024-05-12 15:06 UTC, mmtftr commented on .github/workflows/frontend.yml
why is the frontend workflow deleted? please restore this file

2024-05-12 15:06 UTC, mmtftr commented on backend/src/main/resources/application.properties
> +spring.datasource.password=admin
why do we need this change?

2024-05-12 15:06 UTC, mmtftr commented on .github/workflows/frontend_deploy_staging.yml
> +      - name: Authorize with doctl
can we instead use actions/setup-doctl as mentioned [here](https://docs.digitalocean.com/products/kubernetes/how-to/deploy-using-github-actions/#specify-steps) on step 2

2024-05-12 16:31 UTC, boraykasap commented on backend/src/main/resources/application.properties
> +spring.datasource.password=admin
admin is actually the default one. adminadmin was wrong.

2024-05-12 16:32 UTC, boraykasap commented on .github/workflows/frontend.yml
there was 2 of them with different names. i deleted one.

2024-05-12 16:41 UTC, boraykasap commented on .github/workflows/frontend_deploy_staging.yml
> +      - name: Authorize with doctl
taken into account

2024-05-13 09:48 UTC, mmtftr commented
can we remove on pull request from the frontend test? Just push is enough

2024-05-13 19:16 UTC, mmtftr requested changes

2024-05-13 19:16 UTC, mmtftr commented on .github/workflows/frontend_deploy_staging.yml
> +        uses: digitalocean/action-doctl@v2
please revert this to checkout action

2024-05-13 19:16 UTC, mmtftr commented on .github/workflows/frontend_deploy_staging.yml
> +        run: echo ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} | doctl auth init --context github-actions
if possible this should be the action-doctl using our digitalocean access token

2024-09-24 12:44 UTC, EnesBaserr commented
Closed due to new term.

2024-09-24 12:44 UTC, closed without merging