add recipe controller unit tests
bounswe/bounswe2024group1 pull request #267
Opened 2024-05-15 16:26 UTC by boraykasap

2024-05-15 20:09 UTC, EnesBaserr reviewed
We are going to merge when Recipe related responses finalized.

2024-05-17 15:55 UTC, atakanyasar requested changes

2024-05-17 15:55 UTC, atakanyasar commented on backend/src/test/java/com/group1/cuisines/RecipeControllerTest.java
> +        List<RecipeDto> recipes = Collections.singletonList(new RecipeDto());
RecipeDto is removed.

2024-05-17 15:55 UTC, atakanyasar commented on backend/src/test/java/com/group1/cuisines/RecipeControllerTest.java
> +        RecipeDetailDto recipeDetails = new RecipeDetailDto();
RecipeDetailDto is removed

2024-09-24 12:38 UTC, mmtftr commented
closing due to new term

2024-09-24 12:38 UTC, closed without merging