[FE] Implement Tag and Question References for Answer Creation
bounswe/bounswe2024group1 pull request #624
Opened 2024-12-06 14:41 UTC by asligook

## 📋 Proposed Changes

  - The custom React Markdown component will allow users to mention tags and questions while creating answers.

## Related Issue

## 🧪 Included Tests
- [ ] The user follows the writing format for tags : [tag name](#tag-105), questions: [question title](# q-2)
- [ ] The user clicks on the link and navigates to the related tag and question page.

2024-12-06 17:10 UTC, mmtftr requested changes

2024-12-06 17:10 UTC, mmtftr commented on frontend/src/components/CreateAnswerForm.tsx
> -          <ContentWithSnippets content={content} />
Don't add a new ReactMarkdown here, you should add the custom component to the ReactMarkdown element within ContentWithSnippets

2024-12-08 12:01 UTC, asligook commented on frontend/src/components/CreateAnswerForm.tsx
> -          <ContentWithSnippets content={content} />
That was the most confusing part, thanks for the tip!  Working on it.

2024-12-11 08:30 UTC, mmtftr approved these changes
Thanks a lot, looks good to me

2024-12-11 16:48 UTC, asligook commented
Closes #624.

2024-12-11 16:48 UTC, merged