[Mobile] Bookmarked Questions Page and Bookmark Button on Questions
bounswe/bounswe2024group1 pull request #640
Opened 2024-12-07 20:24 UTC by atakanyasar

## 📋 Proposed Changes

  - Created bookmarked questions page.
  - Put a menu on profile page to navigate bookmarks.
  - Attached bookmark button to add bookmark or remove bookmark to/from a question.

## Related Issue
Closes #607 
Closes #608 

## 🧪 Included Tests
<img src="https://github.com/user-attachments/assets/0f4f5f61-2a94-48bd-ab67-778c7f6ae31f" alt="Image 1" width="300"/>

<img src="https://github.com/user-attachments/assets/ef6aa4b3-b35b-4f16-8b46-7a7b96ead9dc" alt="Image 2" width="300"/>

<img src="https://github.com/user-attachments/assets/15eff712-ca8b-416d-8839-a9d2cd7e54f5" alt="Image 3" width="300"/>

<img src="https://github.com/user-attachments/assets/747ddcbd-7636-4e7e-8425-7f724214b510" alt="Image 4" width="300"/>

2024-12-07 21:09 UTC, mmtftr requested changes
Thanks a lot for the work. The new UI looks a lot nicer than before.

There are a couple of code style requests that I have

2024-12-07 21:09 UTC, mmtftr commented on mobile/services/api/programmingForumComponents.ts
I see that getBookmarkedQuestions has been added here but not inside `openapi.yml`. Please don't manually modify this file, it's automatically generated and must not be edited manually.

Instead, add the API endpoint to `openapi.yml`, then run `yarn generate:api` inside the `mobile/`directory. I'd also appreciate it if you run `yarn generate:api` inside frontend to ensure consistency.

2024-12-07 21:09 UTC, mmtftr commented on mobile/app/bookmarks.tsx
> +    <VStack style={{ flex: 1, padding: 16, marginVertical: 32 }}>
All styles should be using NativeWind/TailwindCSS. Instead of `style={}` use `className=""`

For example,this line should have `className="flex-1 p-4 mt-8"`

2024-12-08 10:37 UTC, atakanyasar commented
I changed sytles and updated api files in both mobile and frontend.

2024-12-08 10:44 UTC, mmtftr approved these changes
Thanks a lot. Looks good to me

2024-12-08 10:56 UTC, merged