[Frontend] Implement Bookmark Page
bounswe/bounswe2024group1 pull request #684
Opened 2024-12-14 18:41 UTC by ozdentarikcan

## 📋 Proposed Changes

  - The bookmark page is implemented.
  - The button that navigates to bookmark page is implemented inside the user profile page.

## Related Issue
Closes #594 

## 🧪 Included Tests
- [X] Bookmarked questions are rendered correctly.

2024-12-14 19:26 UTC, mmtftr requested changes
Thanks a lot for the work here, I just have a couple of style and minor comments

2024-12-14 19:26 UTC, mmtftr commented on frontend/src/routes/profile.tsx
> +              <div style={{ display: 'flex', gap: '15px', justifyContent: 'center', alignItems: 'center' }}>
tailwind classes pls: className="flex gap-4 justify-center items-center"

2024-12-14 19:26 UTC, mmtftr commented on frontend/src/routes/index.tsx
> +    path: "/bookmarkedquestions",
nit: I prefer /bookmarks

2024-12-14 19:26 UTC, mmtftr commented on frontend/src/routes/bookmarked.tsx
> +            ? `Last ${resultListData.totalItems} bookmarked questions shown.`
`totalItems` is not the # of shown items but the total items.

Also, in terms of UX, it doesn't help the user to know they're seeing X items without knowing how many more there are. Instead, let's just tell them the total number of items here. `Bookmarks (${...totalItems})`

2024-12-14 19:26 UTC, mmtftr commented on frontend/src/routes/bookmarked.test.tsx
> +            <Route path="/bookmarked" element={<BookmarkedQuestions />} />
test route != actual route here

2024-12-14 19:40 UTC, ozdentarikcan commented on frontend/src/routes/profile.tsx
> +              <div style={{ display: 'flex', gap: '15px', justifyContent: 'center', alignItems: 'center' }}>
Done.

2024-12-14 19:41 UTC, ozdentarikcan commented on frontend/src/routes/index.tsx
> +    path: "/bookmarkedquestions",
Done. Updated file names to bookmarks as well.

2024-12-14 19:41 UTC, ozdentarikcan commented on frontend/src/routes/bookmarked.tsx
> +            ? `Last ${resultListData.totalItems} bookmarked questions shown.`
Done.

2024-12-14 19:42 UTC, ozdentarikcan commented on frontend/src/routes/bookmarked.test.tsx
> +            <Route path="/bookmarked" element={<BookmarkedQuestions />} />
Updated the test route to /bookmarks with the renaming of the routes.

2024-12-14 19:43 UTC, ozdentarikcan commented
Thanks for the feedback! I updated all the files accordingly.

2024-12-15 07:46 UTC, mmtftr approved these changes
Thanks a lot, looks good to me

2024-12-15 13:45 UTC, merged